version: "3"
services:
  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"

  fastapi:
    image: dsa05037/building-detecting-ai
    ports:
      - "8000:8000"

  springboot:
    image: dsa05037/pnutour-springboot
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
