version: "3"
services:
  mongodb:
    image: mongo
    volumes:
      - ./data/db:/data/db
    container_name: "mongodb"
    ports:
      - 27017:27017
  springboot:
    image: dsa05037/pnutour-springboot
    ports:
      - "8080:8080"
    links:
      - mongodb
  fastapi:
    image: dsa05037/building-detecting-ai
    ports:
      - "8000:8000"